import Link from 'next/link';
import { MessageSquareHeart, Video, LineChart, ShieldCheck, Mic, Sparkles } from 'lucide-react';
import { scenarios } from '@/lib/scenario-catalog';
import { TopNav } from '@/components/site/TopNav';
import { Footer } from '@/components/site/Footer';
import { Halo } from '@/components/site/Halo';
import { Reveal } from '@/components/site/Reveal';
import { HeroPreview } from '@/components/site/HeroPreview';
import { ScenarioCard } from '@/components/site/ScenarioCard';

const STEPS = [
  {
    n: '01',
    title: 'Read the brief',
    body: 'Who the patient is, what they already know, and what a good outcome looks like. The same prep you would get before a real consultation.',
  },
  {
    n: '02',
    title: 'Have the conversation',
    body: 'Speak or type. The patient reacts to how you say things, not only what you say. Warmth settles them; jargon and rushing do not.',
  },
  {
    n: '03',
    title: 'Read the evidence',
    body: 'Scored on empathy, clarity and de-escalation, with every point tied to a specific turn you took. Then run it again.',
  },
];

const FEATURES = [
  {
    icon: MessageSquareHeart,
    title: 'Patients who react',
    body: 'Every character carries a hidden emotional state that moves during the conversation. Acknowledge someone before giving them facts and you will see it land.',
    tone: 'rgba(158, 197, 242, 0.4)',
  },
  {
    icon: Video,
    title: 'Face to face, in real time',
    body: 'Choose a stylised avatar for instant practice, or a photorealistic patient on a live video call that hears you and answers immediately.',
    tone: 'rgba(211, 174, 246, 0.36)',
  },
  {
    icon: LineChart,
    title: 'Feedback with receipts',
    body: 'No vague scores. Each strength and each suggestion quotes the exact turn it came from, so you know precisely what to change.',
    tone: 'rgba(250, 180, 117, 0.36)',
  },
  {
    icon: Mic,
    title: 'Voice first',
    body: 'Speak out loud the way you would in a clinic. Delivery, pacing and word choice are the whole skill, and typing hides all three.',
    tone: 'rgba(158, 178, 153, 0.42)',
  },
];

const SAFETY = [
  'Formative practice only. Nothing here is a competency assessment or a clinical decision aid.',
  'The emotion signal is generated by the same model that plays the patient, so it is not independent ground truth.',
  'Scenarios are fictional. Never enter real patient names or identifiable details.',
  'Sensitive scenarios are flagged for faculty review before they are used in teaching.',
];

const STATS = [
  { k: `${scenarios.length}`, v: 'Scenarios' },
  { k: '3', v: 'Skills scored' },
  { k: 'Live', v: 'Video patients' },
];

export default function HomePage() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100dvh' }}>
      <TopNav />

      <main style={{ flex: 1 }}>
        {/* ---------- HERO ---------- */}
        <section className="halo-wrap" style={{ position: 'relative', overflow: 'hidden' }}>
          <span aria-hidden className="grid-veil" />
          <Halo tone="sage" size="640px" top="-240px" left="-140px" opacity={0.5} drift />
          <Halo tone="apricot" size="520px" top="-120px" right="-120px" opacity={0.4} drift="slow" />
          <Halo tone="lilac" size="460px" top="300px" left="38%" opacity={0.26} drift />

          <div
            className="shell hero-grid"
            style={{
              display: 'grid',
              alignItems: 'center',
              gap: 'clamp(36px, 5vw, 72px)',
              paddingBlock: 'clamp(44px, 5.6vw, 92px)',
            }}
          >
            {/* Copy */}
            <div>
              <Reveal>
                <span className="pill" style={{ marginBottom: 22 }}>
                  <Sparkles size={11} strokeWidth={2.2} style={{ color: 'var(--accent-dim)' }} />
                  For healthcare students
                </span>
              </Reveal>

              <Reveal delay={60}>
                {/* No hard line breaks: text-wrap balance handles the ragging at
                    every width, whereas fixed breaks orphaned short words. */}
                <h1 className="t-display" style={{ maxWidth: '15ch' }}>
                  Practice the hardest part of{' '}
                  <span style={{ color: 'var(--accent-dim)' }}>medicine.</span>
                </h1>
              </Reveal>

              <Reveal delay={130}>
                <p className="t-lede" style={{ marginTop: 24, maxWidth: '46ch' }}>
                  Breaking bad news. De-escalating an angry relative. Sitting with
                  someone who does not want to talk. Rehearse the conversations
                  that decide how care actually feels, before a real patient is on
                  the other side.
                </p>
              </Reveal>

              <Reveal delay={200}>
                <div style={{ display: 'flex', gap: 12, marginTop: 34, flexWrap: 'wrap' }}>
                  <Link href="#scenarios" className="btn btn-primary btn-lg">
                    Choose a scenario
                  </Link>
                  <Link href="#how" className="btn btn-secondary btn-lg">
                    How it works
                  </Link>
                </div>
              </Reveal>

              <Reveal delay={270}>
                <div
                  style={{
                    display: 'flex',
                    gap: 'clamp(24px, 4vw, 44px)',
                    marginTop: 44,
                    paddingTop: 26,
                    borderTop: '1px solid var(--border-sub)',
                    flexWrap: 'wrap',
                  }}
                >
                  {STATS.map((stat) => (
                    <div key={stat.v}>
                      <div
                        style={{
                          fontSize: 26,
                          fontWeight: 700,
                          letterSpacing: '-0.02em',
                          color: 'var(--text-1)',
                          lineHeight: 1.1,
                        }}
                      >
                        {stat.k}
                      </div>
                      <div
                        className="font-mono"
                        style={{
                          fontSize: 9.5,
                          color: 'var(--text-3)',
                          letterSpacing: '0.14em',
                          textTransform: 'uppercase',
                          marginTop: 4,
                        }}
                      >
                        {stat.v}
                      </div>
                    </div>
                  ))}
                </div>
              </Reveal>
            </div>

            {/* Live preview */}
            <Reveal delay={120} className="hero-visual">
              <HeroPreview />
            </Reveal>
          </div>
        </section>

        {/* ---------- HOW IT WORKS ---------- */}
        <section id="how" className="section" style={{ borderTop: '1px solid var(--border-sub)', scrollMarginTop: 72 }}>
          <div className="shell">
            <Reveal>
              <p className="eyebrow">How it works</p>
              <h2 className="t-h1" style={{ marginTop: 14, maxWidth: '20ch' }}>
                Three steps, then do it again.
              </h2>
            </Reveal>

            <div
              className="steps-grid"
              style={{
                display: 'grid',
                gap: 'clamp(20px, 2.6vw, 32px)',
                marginTop: 'clamp(32px, 3.6vw, 54px)',
              }}
            >
              {STEPS.map((step, i) => (
                <Reveal key={step.n} delay={i * 90}>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                    <span
                      className="font-mono"
                      style={{ fontSize: 11, color: 'var(--accent-dim)', letterSpacing: '0.14em' }}
                    >
                      {step.n}
                    </span>
                    <div aria-hidden style={{ height: 1, background: 'var(--border)', width: '100%' }} />
                    <h3 className="t-h2" style={{ fontSize: 'clamp(19px, 1.9vw, 23px)' }}>
                      {step.title}
                    </h3>
                    <p className="t-body">{step.body}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ---------- FEATURES ---------- */}
        <section className="section-tight">
          <div className="shell">
            <Reveal>
              <p className="eyebrow">What makes it useful</p>
              <h2 className="t-h1" style={{ marginTop: 14, maxWidth: '24ch' }}>
                Built around how the conversation actually goes.
              </h2>
            </Reveal>

            <div
              className="features-grid"
              style={{
                display: 'grid',
                gap: 'clamp(14px, 1.6vw, 20px)',
                marginTop: 'clamp(30px, 3.4vw, 50px)',
              }}
            >
              {FEATURES.map((feature, i) => {
                const Icon = feature.icon;
                return (
                  <Reveal key={feature.title} delay={i * 70}>
                    <article
                      className="card lift"
                      style={{
                        position: 'relative',
                        height: '100%',
                        padding: 'clamp(20px, 2.4vw, 28px)',
                        overflow: 'hidden',
                        isolation: 'isolate',
                      }}
                    >
                      <span
                        aria-hidden
                        style={{
                          position: 'absolute',
                          top: -70,
                          left: -50,
                          width: 220,
                          height: 220,
                          zIndex: 0,
                          borderRadius: '50%',
                          background: `radial-gradient(circle, ${feature.tone} 0%, transparent 68%)`,
                          filter: 'blur(34px)',
                          opacity: 0.85,
                          pointerEvents: 'none',
                        }}
                      />
                      <div style={{ position: 'relative', zIndex: 1 }}>
                        <span
                          style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            width: 38,
                            height: 38,
                            borderRadius: 12,
                            background: 'var(--surface-2)',
                            border: '1px solid var(--border-sub)',
                            marginBottom: 16,
                          }}
                        >
                          <Icon size={17} strokeWidth={1.9} style={{ color: 'var(--text-1)' }} />
                        </span>
                        <h3 className="t-h3" style={{ marginBottom: 8 }}>
                          {feature.title}
                        </h3>
                        <p className="t-body">{feature.body}</p>
                      </div>
                    </article>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </section>

        {/* ---------- SCENARIOS ---------- */}
        <section id="scenarios" className="section" style={{ scrollMarginTop: 72 }}>
          <div className="shell">
            <Reveal>
              {/* Explicit grid rather than flex-wrap: with wrap, the heading's
                  max-content width pushed the paragraph onto its own line and
                  stranded it in a narrow column. */}
              <div
                className="scenarios-head"
                style={{ display: 'grid', alignItems: 'end', gap: 'clamp(16px, 3vw, 40px)' }}
              >
                <div>
                  <p className="eyebrow">Scenarios</p>
                  <h2 className="t-h1" style={{ marginTop: 14, maxWidth: '20ch' }}>
                    Pick who you need to face today.
                  </h2>
                </div>
                <p className="t-body" style={{ maxWidth: '38ch' }}>
                  Each one runs about ten exchanges. Choose a stylised avatar or a
                  live video patient when you start.
                </p>
              </div>
            </Reveal>

            <div
              className="scenarios-grid"
              style={{
                display: 'grid',
                gap: 'clamp(14px, 1.6vw, 20px)',
                marginTop: 'clamp(30px, 3.2vw, 46px)',
              }}
            >
              {scenarios.map((scenario, i) => (
                <Reveal key={scenario.id} delay={i * 70}>
                  <ScenarioCard scenario={scenario} index={i} />
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ---------- SAFETY ---------- */}
        <section id="safety" className="section-tight" style={{ scrollMarginTop: 72 }}>
          <div className="shell">
            <Reveal>
              <div
                className="card-quiet safety-card"
                style={{
                  display: 'grid',
                  gap: 'clamp(24px, 4vw, 52px)',
                  padding: 'clamp(24px, 3.4vw, 44px)',
                  borderRadius: 'var(--r-xl)',
                }}
              >
                <div>
                  <span
                    style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      width: 38,
                      height: 38,
                      borderRadius: 12,
                      background: 'var(--surface)',
                      border: '1px solid var(--border)',
                      marginBottom: 16,
                    }}
                  >
                    <ShieldCheck size={17} strokeWidth={1.9} style={{ color: 'var(--accent-dim)' }} />
                  </span>
                  <p className="eyebrow">Read this first</p>
                  <h2 className="t-h2" style={{ marginTop: 12, maxWidth: '20ch' }}>
                    An honest account of what this can and cannot do.
                  </h2>
                </div>

                <ul
                  style={{
                    margin: 0,
                    padding: 0,
                    listStyle: 'none',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 14,
                  }}
                >
                  {SAFETY.map((item) => (
                    <li
                      key={item}
                      style={{
                        display: 'flex',
                        gap: 12,
                        fontSize: 13.5,
                        lineHeight: 1.6,
                        color: 'var(--text-2)',
                      }}
                    >
                      <span
                        aria-hidden
                        style={{
                          marginTop: 7,
                          width: 5,
                          height: 5,
                          borderRadius: '50%',
                          background: 'var(--accent)',
                          flexShrink: 0,
                        }}
                      />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </Reveal>
          </div>
        </section>

        {/* ---------- CLOSING CTA ---------- */}
        <section className="section halo-wrap" style={{ position: 'relative', overflow: 'hidden' }}>
          <Halo tone="sage" size="620px" bottom="-320px" left="50%" opacity={0.42} drift />
          <div className="shell" style={{ textAlign: 'center' }}>
            <Reveal>
              <h2 className="t-h1" style={{ margin: '0 auto', maxWidth: '18ch' }}>
                The first time should not be the real time.
              </h2>
              <p className="t-lede" style={{ margin: '20px auto 0', maxWidth: '44ch' }}>
                Pick a patient and start talking. It takes about five minutes.
              </p>
              <div
                style={{
                  display: 'flex',
                  gap: 12,
                  marginTop: 32,
                  justifyContent: 'center',
                  flexWrap: 'wrap',
                }}
              >
                <Link href="#scenarios" className="btn btn-primary btn-lg">
                  Choose a scenario
                </Link>
                <Link href="/avatars" className="btn btn-secondary btn-lg">
                  Meet the patients
                </Link>
              </div>
            </Reveal>
          </div>
        </section>
      </main>

      <Footer />

      <style>{`
        .hero-grid { grid-template-columns: 1.08fr 0.92fr; }
        .steps-grid { grid-template-columns: repeat(3, 1fr); }
        .features-grid { grid-template-columns: repeat(2, 1fr); }
        .scenarios-grid { grid-template-columns: repeat(2, 1fr); }
        .scenarios-head { grid-template-columns: minmax(0, 1fr) minmax(230px, 320px); }
        .safety-card { grid-template-columns: 1fr 1fr; align-items: start; }

        @media (max-width: 1080px) {
          .hero-grid { grid-template-columns: 1fr; }
          .hero-visual { max-width: 460px; }
        }

        @media (max-width: 860px) {
          .steps-grid { grid-template-columns: 1fr; gap: 30px; }
          .features-grid { grid-template-columns: 1fr; }
          .scenarios-grid { grid-template-columns: 1fr; }
          .scenarios-head { grid-template-columns: 1fr; }
          .safety-card { grid-template-columns: 1fr; }
        }

        @media (max-width: 520px) {
          .hero-visual { max-width: 100%; }
        }
      `}</style>
    </div>
  );
}
